### ISSUE TITLE
TypeError: Expected bool, got 1.0 of type 'float' instead.

### ISSUE THREAD

**Issue by terminal-zyx** [Guo-Xiaoqing/Triple-ANet#4]
Traceback (most recent call last):
  File "Triple_ANet_train.py", line 268, in <module>
    feature, pred, ys_, train_end_points, reg, regularization = triple_anet(xs, ys, label_count, drop_rate=1.0, decay=0.9, growth_k=growth_k, trainable = True, reuse=False)    
  File "Triple_ANet_train.py", line 198, in triple_anet
    training=trainable, reuse=reuse, scope='conv2pool_1')
  File "Triple_ANet_train.py", line 46, in conv2pool
    x = batch_norm(x, training, scope=scope + '_batch1')

**Comment by Guo-Xiaoqing** [comment]
Please modify “ File "Triple_ANet_train.py", line 46, in conv2pool
x = batch_norm(x, training, scope=scope + '_batch1')” to “ File "Triple_ANet_train.py", line 46, in conv2pool
x = batch_norm(x, training=training, scope=scope + '_batch1')”
